name: CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "test selection"
        required: true
        type: choice
        default: "dev"
        options:
        - dev
        - test
        - prod


permissions: read-all

jobs:
  Deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: v0.52.0

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact

    - name: Setup Tofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: "1.7.3"
        tofu_wrapper: false

    - name: Tofu Init
      run: tofu init

    - name: Tofu Fmt
      run: tofu fmt --recursive

    - name: Tofu Validate
      run: tofu validate

    - name: Todu Plan
      run: tofu plan

    - name: Tofu Apply
      run: tofu apply -auto-approve -var-file="environments/${{ inputs.environment }}.tfvars"
