name: CI

on:
  push:
    branches: ["main"]

permissions: read-all

jobs:
  Intergration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkov GitHub Action
      uses: bridgecrewio/checkov-action@v12
      with:
        ## This will add both a CLI output to the console and create a results.sarif file
        output_format: cli
        output_file_path: console

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}
        # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: "arn:aws:iam::255945442255:role/GitHubAction-AssumeRoleWithAction"
        role-session-name: GitHub_to_AWS_via_FederatedOIDC


    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: v0.52.0

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact

    - name: Setup Tofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: "1.7.3"
        tofu_wrapper: false

    - name: Tofu Init
      run: tofu init

    - name: Tofu Fmt
      run: tofu fmt --recursive

    - name: Tofu Validate
      run: tofu validate

    - name: Todu Plan
      run: tofu plan
